export const TOGGLE_CART_STATE = 'TOGGLE_CART_STATE';

export const CART_RECEIVE_DATA = 'CART_RECEIVE_DATA';
export const CART_RECEIVE_DATA_ERROR = 'CART_RECEIVE_DATA_ERROR';

//controll action constants
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUN';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUN';
