export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const RESTORE_PASSWORD_SUCCESS = 'RESTORE_PASSWORD_SUCCESS';
export const RESTORE_PASSWORD_FAILURE = 'RESTORE_PASSWORD_FAILURE';

export const CREATING_ACCOUNT_SUCCESS = 'CREATING_ACCOUNT_SUCCESS';
export const CREATING_ACCOUNT_FAILURE = 'CREATING_ACCOUNT_FAILURE';

export const PASSWORD_RESET_SENT = 'PASSWORD_RESET_SENT';
