export const PRODUCTPAGE_RECEIVE_DATA = 'PRODUCTPAGE_RECEIVE_DATA';
export const PRODUCTPAGE_RECEIVE_DATA_ERROR = 'PRODUCTPAGE_RECEIVE_DATA_ERROR';

export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT ';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT ';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';

export const ADDING_PRODUCT_TO_WISHLIST_SUCCESS = 'ADDING_PRODUCT_TO_WISHLIST_SUCCESS';
export const ADDING_PRODUCT_TO_WISHLIST_FAILURE = 'ADDING_PRODUCT_TO_WISHLIST_FAILURE';

export const REMOVE_FROM_WISH_LIST_SUCCESS = 'REMOVE_FROM_WISH_LIST_SUCCESS';
export const REMOVE_FROM_WISH_LIST_FAILURE = 'REMOVE_FROM_WISH_LIST_FAILURE';