export const PRODUCTPAGE_RECEIVE_DATA = 'PRODUCTPAGE_RECEIVE_DATA';
export const PRODUCTPAGE_RECEIVE_DATA_ERROR = 'PRODUCTPAGE_RECEIVE_DATA_ERROR';

export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT ';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT ';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';
