export const USER_DATA_RECEIVED = 'USER_DATA_RECEIVED';
export const USER_DATA_SAVED = 'USER_DATA_SAVED';

export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const TOGGLE_SUCCESS_PANEL = 'TOGGLE_SUCCESS_PANEL';

export const USER_DATA_NOT_SAVED = 'USER_DATA_NOT_SAVED';
export const USER_PASSWORD_NOT_SAVED = 'USER_PASSWORD_NOT_SAVED';
