export const TOGGLE_CATEGORIES = 'TOGGLE_CATEGORIES';
export const SHOP_PRODUCTS_RECEIVE_DATA = 'SHOP_PRODUCTS_RECEIVE_DATA';
export const SHOP_PRODUCTS_RECEIVE_DATA_ERROR = 'SHOP_PRODUCTS_RECEIVE_DATA_ERROR';